
%%
colors = {'c','k','b','g','r','m'};
markers = {'+','o','.','^','v','*','s','<','>','p','h'};
figure
hold on
load('3D_HT.mat')
plot3(groupConectivity(metTypes.AA_mets),groupCost(metTypes.AA_mets),Sens(metTypes.AA_mets),[colors{1},markers{1}])
plot3(groupConectivity(metTypes.CB_mets),groupCost(metTypes.CB_mets),Sens(metTypes.CB_mets),[colors{1},markers{2}])
plot3(groupConectivity(metTypes.Nuc_mets),groupCost(metTypes.Nuc_mets),Sens(metTypes.Nuc_mets),[colors{1},markers{3}])
plot3(groupConectivity(metTypes.TAG_mets),groupCost(metTypes.TAG_mets),Sens(metTypes.TAG_mets),[colors{1},markers{4}])
plot3(groupConectivity(metTypes.DAG_mets),groupCost(metTypes.DAG_mets),Sens(metTypes.DAG_mets),[colors{1},markers{5}])
plot3(groupConectivity(metTypes.MAG_mets),groupCost(metTypes.MAG_mets),Sens(metTypes.MAG_mets),[colors{1},markers{6}])
plot3(groupConectivity(metTypes.Pe_mets),groupCost(metTypes.Pe_mets),Sens(metTypes.Pe_mets),[colors{1},markers{7}])
plot3(groupConectivity(metTypes.Pg_mets),groupCost(metTypes.Pg_mets),Sens(metTypes.Pg_mets),[colors{1},markers{8}])
plot3(groupConectivity(metTypes.As_mets),groupCost(metTypes.As_mets),Sens(metTypes.As_mets),[colors{1},markers{9}])
plot3(groupConectivity(metTypes.Dgts_mets),groupCost(metTypes.Dgts_mets),Sens(metTypes.Dgts_mets),[colors{1},markers{10}])
plot3(groupConectivity(metTypes.Dgdg_mets),groupCost(metTypes.Dgdg_mets),Sens(metTypes.Dgdg_mets),[colors{1},markers{11}])

load('3D_PA.mat')
plot3(groupConectivity(metTypes.AA_mets),groupCost(metTypes.AA_mets),Sens(metTypes.AA_mets),[colors{2},markers{1}])
plot3(groupConectivity(metTypes.CB_mets),groupCost(metTypes.CB_mets),Sens(metTypes.CB_mets),[colors{2},markers{2}])
plot3(groupConectivity(metTypes.Nuc_mets),groupCost(metTypes.Nuc_mets),Sens(metTypes.Nuc_mets),[colors{2},markers{3}])
plot3(groupConectivity(metTypes.TAG_mets),groupCost(metTypes.TAG_mets),Sens(metTypes.TAG_mets),[colors{2},markers{4}])
plot3(groupConectivity(metTypes.DAG_mets),groupCost(metTypes.DAG_mets),Sens(metTypes.DAG_mets),[colors{2},markers{5}])
plot3(groupConectivity(metTypes.MAG_mets),groupCost(metTypes.MAG_mets),Sens(metTypes.MAG_mets),[colors{2},markers{6}])
plot3(groupConectivity(metTypes.Pe_mets),groupCost(metTypes.Pe_mets),Sens(metTypes.Pe_mets),[colors{2},markers{7}])
plot3(groupConectivity(metTypes.Pg_mets),groupCost(metTypes.Pg_mets),Sens(metTypes.Pg_mets),[colors{2},markers{8}])
plot3(groupConectivity(metTypes.As_mets),groupCost(metTypes.As_mets),Sens(metTypes.As_mets),[colors{2},markers{9}])
plot3(groupConectivity(metTypes.Dgts_mets),groupCost(metTypes.Dgts_mets),Sens(metTypes.Dgts_mets),[colors{2},markers{10}])
plot3(groupConectivity(metTypes.Dgdg_mets),groupCost(metTypes.Dgdg_mets),Sens(metTypes.Dgdg_mets),[colors{2},markers{11}])

load('3D_Pt.mat')
plot3(groupConectivity(metTypes.AA_mets),groupCost(metTypes.AA_mets),Sens(metTypes.AA_mets),[colors{3},markers{1}])
plot3(groupConectivity(metTypes.CB_mets),groupCost(metTypes.CB_mets),Sens(metTypes.CB_mets),[colors{3},markers{2}])
plot3(groupConectivity(metTypes.Nuc_mets),groupCost(metTypes.Nuc_mets),Sens(metTypes.Nuc_mets),[colors{3},markers{3}])
plot3(groupConectivity(metTypes.TAG_mets),groupCost(metTypes.TAG_mets),Sens(metTypes.TAG_mets),[colors{3},markers{4}])
plot3(groupConectivity(metTypes.DAG_mets),groupCost(metTypes.DAG_mets),Sens(metTypes.DAG_mets),[colors{3},markers{5}])
plot3(groupConectivity(metTypes.MAG_mets),groupCost(metTypes.MAG_mets),Sens(metTypes.MAG_mets),[colors{3},markers{6}])
plot3(groupConectivity(metTypes.Pe_mets),groupCost(metTypes.Pe_mets),Sens(metTypes.Pe_mets),[colors{3},markers{7}])
plot3(groupConectivity(metTypes.Pg_mets),groupCost(metTypes.Pg_mets),Sens(metTypes.Pg_mets),[colors{3},markers{8}])
plot3(groupConectivity(metTypes.As_mets),groupCost(metTypes.As_mets),Sens(metTypes.As_mets),[colors{3},markers{9}])
plot3(groupConectivity(metTypes.Dgts_mets),groupCost(metTypes.Dgts_mets),Sens(metTypes.Dgts_mets),[colors{3},markers{10}])
plot3(groupConectivity(metTypes.Dgdg_mets),groupCost(metTypes.Dgdg_mets),Sens(metTypes.Dgdg_mets),[colors{3},markers{11}])

load('3D_Yl.mat')
plot3(groupConectivity(metTypes.AA_mets),groupCost(metTypes.AA_mets),Sens(metTypes.AA_mets),[colors{4},markers{1}])
plot3(groupConectivity(metTypes.CB_mets),groupCost(metTypes.CB_mets),Sens(metTypes.CB_mets),[colors{4},markers{2}])
plot3(groupConectivity(metTypes.Nuc_mets),groupCost(metTypes.Nuc_mets),Sens(metTypes.Nuc_mets),[colors{4},markers{3}])
plot3(groupConectivity(metTypes.TAG_mets),groupCost(metTypes.TAG_mets),Sens(metTypes.TAG_mets),[colors{4},markers{4}])
plot3(groupConectivity(metTypes.DAG_mets),groupCost(metTypes.DAG_mets),Sens(metTypes.DAG_mets),[colors{4},markers{5}])
plot3(groupConectivity(metTypes.MAG_mets),groupCost(metTypes.MAG_mets),Sens(metTypes.MAG_mets),[colors{4},markers{6}])
plot3(groupConectivity(metTypes.Pe_mets),groupCost(metTypes.Pe_mets),Sens(metTypes.Pe_mets),[colors{4},markers{7}])
plot3(groupConectivity(metTypes.Pg_mets),groupCost(metTypes.Pg_mets),Sens(metTypes.Pg_mets),[colors{4},markers{8}])
plot3(groupConectivity(metTypes.As_mets),groupCost(metTypes.As_mets),Sens(metTypes.As_mets),[colors{4},markers{9}])
plot3(groupConectivity(metTypes.Dgts_mets),groupCost(metTypes.Dgts_mets),Sens(metTypes.Dgts_mets),[colors{4},markers{10}])
plot3(groupConectivity(metTypes.Dgdg_mets),groupCost(metTypes.Dgdg_mets),Sens(metTypes.Dgdg_mets),[colors{4},markers{11}])

load('3D_CHO.mat')
plot3(groupConectivity(metTypes.AA_mets),groupCost(metTypes.AA_mets),Sens(metTypes.AA_mets),[colors{5},markers{1}])
plot3(groupConectivity(metTypes.CB_mets),groupCost(metTypes.CB_mets),Sens(metTypes.CB_mets),[colors{5},markers{2}])
plot3(groupConectivity(metTypes.Nuc_mets),groupCost(metTypes.Nuc_mets),Sens(metTypes.Nuc_mets),[colors{5},markers{3}])
plot3(groupConectivity(metTypes.TAG_mets),groupCost(metTypes.TAG_mets),Sens(metTypes.TAG_mets),[colors{5},markers{4}])
plot3(groupConectivity(metTypes.DAG_mets),groupCost(metTypes.DAG_mets),Sens(metTypes.DAG_mets),[colors{5},markers{5}])
plot3(groupConectivity(metTypes.MAG_mets),groupCost(metTypes.MAG_mets),Sens(metTypes.MAG_mets),[colors{5},markers{6}])
plot3(groupConectivity(metTypes.Pe_mets),groupCost(metTypes.Pe_mets),Sens(metTypes.Pe_mets),[colors{5},markers{7}])
plot3(groupConectivity(metTypes.Pg_mets),groupCost(metTypes.Pg_mets),Sens(metTypes.Pg_mets),[colors{5},markers{8}])
plot3(groupConectivity(metTypes.As_mets),groupCost(metTypes.As_mets),Sens(metTypes.As_mets),[colors{5},markers{9}])
plot3(groupConectivity(metTypes.Dgts_mets),groupCost(metTypes.Dgts_mets),Sens(metTypes.Dgts_mets),[colors{5},markers{10}])
plot3(groupConectivity(metTypes.Dgdg_mets),groupCost(metTypes.Dgdg_mets),Sens(metTypes.Dgdg_mets),[colors{5},markers{11}])


xlabel('Conectivity')
ylabel('Cost')
zlabel('Sensitivity')
legend('AA','CB','Nuc','TAG','DAG','MAG','Pe','Pg','As','Dgts')

%%
figure
hold on
load('3D_HT.mat')
plot3(groupConectivity,groupCost,growth_Cod,'o')
load('3D_PA.mat')
plot3(groupConectivity,groupCost,growth_Cod,'o')
load('3D_Pt.mat')
plot3(groupConectivity,groupCost,growth_Cod,'o')
load('3D_CHO.mat')
plot3(groupConectivity,groupCost,growth_Cod,'o')

xlabel('Conectivity')
ylabel('Cost')
zlabel('Codependence')
